name: Generate terraform docs
on:
  push

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4

      - name: Render terraform docs and push changes back to branch
        uses: terraform-docs/gh-actions@v1.3.0
        with:
          working-dir: cde-full-setup/,cde-iam-setup/
          output-file: README.md
          output-method: inject
          git-push: "true"
          git-commit-message: "docs: automated update of terraform docs"